### ISSUE TITLE
Issue 

### ISSUE THREAD

**Issue by Anujmoglix** [adelowo/pusher-react-native-gifted-chat#1]
Hi ,
 I tried to run this and getting following issue 
![Selection_129](https://user-images.githubusercontent.com/26056096/58633991-bcf9ad80-8307-11e9-9ccb-c8e1b3e6c5d6.png)

**Comment by adelowo** [comment]
Kindly follow the instructions in the `README.MD` 

> Update line 5 - 9 of MyChat.js with your credentials.

**Comment by Anujmoglix** [comment]
I missed that , I need one more help . I hv created account in pusher but not able to get 

**const CHATKIT_ROOM_ID = 'ROOM_ID';**. where is it ?

**Comment by adelowo** [comment]
Go to the ___Debug console___ in Pusher's dashboard and create a room. You will be able to see the ID of the room once created
